# this recipe is for local building
# see https://github.com/conda-forge/conda-tree-feedstock/blob/master/recipe/meta.yaml
# for the conda-forge recipe

package:
  name: conda-tree
  version: dev

source:
  path: .

build:
  number: 0
  noarch: python
  script:
    - "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - conda-tree = conda_tree:main

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - networkx
    - conda

test:
  commands:
    - conda-tree -h

about:
  home: https://github.com/rvalieris/conda-tree
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'conda dependency tree helper'
  dev_url: https://github.com/rvalieris/conda-tree
  doc_url: https://github.com/rvalieris/conda-tree
