package:
  name: conda-tree
  version: "0.0.5"

source:
  git_url: https://github.com/rvalieris/conda-tree.git
  git_rev: v0.0.5

requirements:
  host:
    - python
    - pip
    - setuptools

  run:
    - python
    - networkx
    - conda

build:
  number: 0
  noarch: generic
  script:
    - "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - conda-tree = conda_tree:main

test:
  commands:
    - conda-tree -h

about:
  home: https://github.com/rvalieris/conda-tree
  license: MIT
  license_file: LICENSE
